name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons
        
      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation --no-tree-shake-icons
        
      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: "latest"
          name: "Latest Release"
          body: "Auto-generated APK build from the latest master branch."
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
